### ISSUE TITLE
Ajouter une licence aux depots qui n'en ont pas une

### ISSUE THREAD

**Issue by maukoquiroga** [sgmap/beta.gouv.fr#719]
Dans le cadre du #655, @gregoirenovel a découvert que 

    D'après mes (rapides) recherches, sur 21 projets qui dont le code est ouvert :

    - 16 ont une license AGPL
    - 4 n'ont pas de license
    - 1 a une license MIT

Je vais proposer donc d'en donner une, [AGPL-3.0 ou autre](https://github.com/sgmap/beta.gouv.fr/wiki/Publier#licence), aux depots dans cette liste.

## Startups

- [x] Plante & moi back sgmap/plante-et-moi-backend#1
- [x] Plante & moi front sgmap/plante-et-moi#21
- [x] Opensimplif sgmap/opensimplif#1
- [x] Open Académie sgmap/open-academie#4
- [x] Open Académie Next sgmap/open-academie-next#30
- [x] Retraite sgmap/retraite#4
- [x] Paie front-end sgmap/paie-www#14

## APIs

- [x] Svair API sgmap/api-avis-imposition#1
- [x] CPA API sgmap/api-cpa#9
- [x] API Sirene sgmap/sirene_as_api#2
- [x] API Particulier Slate sgmap/api-particulier-slate#2

## Autres

- [x] verif.site sgmap/verif.site#62
- [x] OpenFisca cd98 sgmap/openfisca-cd93#1
- [x] OpenFisca Paris sgmap/openfisca-paris#8
- [x] betaGouvBot sgmap/betaGouvBot#72

**Definition of Done :** Avoir crée les issues (ça revient aux équipes produit après)

**Comment by jdesboeufs** [comment]
C'est aux équipes produit de définir ça.
S'il devait y avoir une licence par défaut, elle devrait être permissive.

Pour tout ce qui touche à la géo nous allons migrer l'essentiel vers MIT. Toutes les briques sont désormais chez Etalab.

trashadvisor est un prototype développé avec le Ministère de l'Environnement. Pas pertinent d'établir une licence. Code à transférer plutôt.

Pour les briques OPS : imposer une servitude ne fait pas de sens, une licence permissive serait beaucoup plus adapté.
Pareil pour les briques API Entreprise ou Particulier.

**Comment by maukoquiroga** [comment]
Merci @jdesboeufs 😃 

> C'est aux équipes produit de définir ça.

Tout à fait. Je vais changer la description de l'issue et modifier la liste.

> S'il devait y avoir une licence par défaut, elle devrait être permissive.

Comme tu l'as bien dit, c'est aux équipes produit de définir ça. Dans tous le cas, j'ajoute le [lien vers le wiki]((https://github.com/sgmap/beta.gouv.fr/wiki/Publier#licence)) dans l'hypothèse que cela represent le fruit d'un débat qui a déjà eu lieu.

> Pour tout ce qui touche à la géo nous allons migrer l'essentiel vers MIT. Toutes les briques sont désormais chez Etalab.

👍 

> trashadvisor est un prototype développé avec le Ministère de l'Environnement. Pas pertinent d'établir une licence. Code à transférer plutôt.

Mmm... je l'enlève de la liste pour l'instant.

> Pour les briques OPS : imposer une servitude ne fait pas de sens, une licence permissive serait beaucoup plus adapté.

Je suis d'accord. Dans tous le cas, je vais poser la question directement aux équipes.

> Pareil pour les briques API Entreprise ou Particulier.

Même histoire.
