### ISSUE TITLE
Create a timer for the portfolio review

### ISSUE THREAD

**Issue by maukoquiroga** [sgmap/beta.gouv.fr#760]
### Goal

- Ease the management of time during the review
- Incentivise the regular update of startups and their status in the site
- Create a shareable tool for people to implement their own portfolio review

### Job story

    When I'm in the open space and it's 11h59,
    And I'm writing my post-its for the portfolio review,
    And I'm at the other corner of the startup's wall,
    And I've left my +4.0 eyeglasses at home,
    And it's already 12:05 and we haven't started yet because we're setting the timer,
    And it's now 12:10, we've started but some people do not respect de 1m rule,
    And it's now 12:20 and a group of three patronise us with a conversation that could wait,
    And it's now 12:30, I'm hangry* and we haven't finished yet,
    And I've stopped paying attention to the review and started thinking that for next week's;

    I'd love the timer to be ready at 12 o'clock,
    And to have a timer in this corner of the room too,
    And to be able to read the pitch in case I'm too far to catch it,
    And to be able to see the screenshot as one image is worth a million words,
    And to avoid people talking when there's nothing to say
    And to avoid people from improvising (oh I hate that !);

    For me to keep my attention levels up,
    To get the most of the review,
    And to stop wasting my time.
    
**\*hangry:** anger + hungry

### TODO

- [x] /startups api endpoint
- [ ] Timer thats picks startups randomly and assigns them 1m + 2' reverse counter clockwise
- [ ] Add startup's pitch to each time slot
- [ ] Add startup's screenshot to each time slot
- [ ] Add a « next » option to skip a time slot
- [ ] Add a 5m + 15' after the last startup (general broadcast after policies explanation)

**Comment by gregoirenovel** [comment]
Done with https://github.com/sgmap/standup/
